import localFont from 'next/font/local'

export const neueRegrade = localFont({
    src:[
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Light.otf',
            weight:'300',
            style:'normal'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Light-Italic.otf',
            weight:'300',
            style:'italic'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Regular.otf',
            weight:'400',
            style:'normal'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Regular-Italic.otf',
            weight:'400',
            style:'italic'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Medium.otf',
            weight:'500',
            style:'normal'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Medium-Italic.otf',
            weight:'500',
            style:'italic'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Semibold.otf',
            weight:'600',
            style:'normal'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Bold.otf',
            weight:'700',
            style:'normal'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Bold-Italic.otf',
            weight:'700',
            style:'italic'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-Extrabold.otf',
            weight:'800',
            style:'normal'
        },
        {
            path:'../../public/fonts/NeueRegrade/Neue-Regrade-ExtraBold-Italic.otf',
            weight:'800',
            style:'italic'
        }
    ]
})